- name: Install required tools
  hosts: localhost
  become: yes

  tasks:
    - name: Check if Java 17 is installed
      command: java --version
      register: java_check
      ignore_errors: true
      changed_when: false

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        update_cache: yes
      when: java_check.rc != 0

    - name: Check if Maven is installed
      command: mvn --version
      register: maven_check
      ignore_errors: true
      changed_when: false

    - name: Install Maven
      apt:
        name: maven
        update_cache: yes
      when: maven_check.rc != 0

    - name: Check if Node.js 16.8.0 is installed
      command: node --version
      register: node_check
      ignore_errors: true
      changed_when: false

    - name: Install Node.js 16.8.0
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs
      when: node_check.rc != 0

    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: true
      changed_when: false

    - name: ensure repository key is installed
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: ensure docker registry is available
      apt_repository:
        repo: 'deb https://download.docker.com/linux/ubuntu bionic stable'
        state: present

    - name: ensure docker and dependencies are installed
      apt:
        name: docker-ce
        update_cache: yes

    - name: Add Ubuntu user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted

    - name: Check if PostgreSQL container is already running
      command: docker inspect -f '{{.State.Running}}' postgres_container
      register: postgres_container_status
      changed_when: false
      failed_when: false

    - name: Run Docker command
      command: >
        docker run -d
        --name postgres_container
        -e POSTGRES_USER=postgres
        -e POSTGRES_PASSWORD=postgres
        -e POSTGRES_DB=themoviedb
        -p 5432:5432
        postgres:latest
      when: postgres_container_status.stdout != "true"
